feat(lpa-submissions-e2e-tests): add other policies page
Planning-Inspectorate/appeal-planning-decision pull request #1110
Opened 2021-05-18 10:31 UTC by swdpcomputing

## Ticket Number

https://pins-ds.atlassian.net/browse/AS-17

## Description of change

add other policies page

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [x] My commit history in this PR is linear
- [x] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2021-05-18 13:24 UTC, a6software approved these changes
LGTM

2021-05-18 17:13 UTC, davehlewis requested changes
There are also too few commits for this - should be 1 for tests, 1 for web app work, and 1 for reply service work. This is because although in the same repo they are discrete packages. At the very least web app and reply service need to be separate as it will mess with versioning (the reply service work here is a fix not a feat for example).

2021-05-19 11:31 UTC, swdpcomputing commented on lpa-submissions-e2e-tests/cypress/integration/otherRelevantPolicies.feature
> +  #   # Scenario: AC16 PDF & Horizon
Agreed. Removed.

2021-05-19 11:31 UTC, swdpcomputing commented on lpa-submissions-e2e-tests/cypress/integration/otherRelevantPolicies/otherRelevantPolicies.step.js
> +  cy.checkPageA11y(`/${defaultPathId}/${page.url}`);
Agreed, removed.

2021-05-19 13:13 UTC, davehlewis approved these changes

2021-05-19 13:50 UTC, merged