Feature/as 41 implement cookies page
Planning-Inspectorate/appeal-planning-decision pull request #1182
Opened 2021-05-28 13:05 UTC by a6software

## Ticket Number

https://pins-ds.atlassian.net/browse/AS-

## Description of change

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [ ] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2021-05-28 14:05 UTC, davehlewis requested changes
I have done half of the review - there is simply too much in this PR to be able to manage it all.

I would highly recommend splitting this out. I have some concerns of how this works with the common module, especially moving so much out at once. I appreciate the code is genuinely common but I would rather see a ticket to manage that in isolation. I wasn't in the 3A's but a lot of this seems outside the limits of the system.

Regarding the e2e tests - I appreciate these mirror Team 1 for ease, however I think the 7 AC's from the ticket have become 6 different feature files by my count. That seems extraneous. For things like the disabling of JS - we have made use of tagging in order to keep the features aligned.

There are some parts of the team 2 application that have not been considered, which is understandable. For now take a look at the changes I have recommended and see what you think.

I will take a look at the rest early next week, there is just too much to cover for now.

2021-05-28 14:05 UTC, davehlewis commented on packages/lpa-questionnaire-web-app/src/middleware/get-previous-page-path.js
> +const { VIEW } = require('../lib/views');
We already have a method for getting previous page, please refer to one of the other views

2021-06-25 07:50 UTC, rcmsoftwaredevelopment approved these changes

2021-06-29 16:55 UTC, rcmsoftwaredevelopment commented on lpa-submissions-e2e-tests/cypress/integration/common/cookies.js
> +  cy.confirmCookiePolicy(expectedCookiePolicy);
Point noted and used - Thank you for your help.

2021-06-30 11:56 UTC, closed without merging