refactor(rendering 'your name' for 'appellant name' if not agent): re…
Planning-Inspectorate/appeal-planning-decision pull request #1664
Opened 2021-09-01 05:41 UTC by biroldif

…nder 'Your name' if not agent

## Ticket Number
https://pins-ds.atlassian.net/browse/AS-2307

## Description of change
rendering 'your name' for 'appellant name' if not agent

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [ ] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2021-09-01 08:44 UTC, swdpcomputing requested changes

2021-09-01 08:44 UTC, swdpcomputing commented on packages/forms-web-app/src/views/your-planning-appeal/index.njk
> +      {%- if item.status != 'CANNOT START YET' %}
Is this block indented correctly?

2021-09-01 08:44 UTC, swdpcomputing commented
Was this PR posted in build teams?

2021-09-03 11:00 UTC, karunak21 commented
> Was this PR posted in build teams?
It was not posted in build teams, this is a change to the Cypress e2e tests. Shall I ask Birol to post it?

2021-09-03 11:37 UTC, rcmsoftwaredevelopment approved these changes

2021-09-03 13:36 UTC, karunak21 approved these changes
All the cypress tests looks good to me

2021-09-03 13:59 UTC, merged