feat(as-3017): store file metadata in blob storage rather than cosmos db
Planning-Inspectorate/appeal-planning-decision pull request #1670
Opened 2021-09-02 11:11 UTC by shepda

## Ticket Number
https://pins-ds.atlassian.net/browse/AS-3017

## Description of change
Store the file metadata in blob storage as attributes of the uploaded file instead of in Cosmos DB.

Updated and added new unit tests for the changed files but not added missing unit tests for unchanged files, which is something that should be done at a later date.

Have not removed the mongo functionality as it'll be needed for the migration endpoint and this can be removed in a future ticket with the migration endpoint once the migration has been done. 

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [x] My commit history in this PR is linear
- [x] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2021-09-02 14:19 UTC, swdpcomputing requested changes

2021-09-02 15:26 UTC, shepda commented on packages/document-service-api/src/controllers/documents.js
> +  initContainerClient,
As discussed, these could be moved into a common function but with the number of params that would need to be passed to the common function it's not necessarily going to make the parent code any shorter.

2021-09-02 15:27 UTC, shepda commented on packages/document-service-api/src/controllers/documents.js
>      const displayBase64 = req.query.base64 === 'true';
Yep fair enough, I've changed it

2021-09-02 15:27 UTC, shepda commented on packages/document-service-api/src/lib/blobStorage.spec.js
> +    it('should return true when the metadata is fetched successfully', async () => {
Well spotted, I've changed it

2021-09-02 22:22 UTC, rcmsoftwaredevelopment requested changes
1) Can we have some documentation for other devs/testers on how this can be tested locally and where to look in the Azure blob storage.
2) Can the docker file under the root directory be amended so for the document storage api removes all dependancies to mongodb.

2021-09-03 07:42 UTC, swdpcomputing submitted a review, later dismissed

2021-09-03 08:12 UTC, shepda commented
>     1. Can we have some documentation for other devs/testers on how this can be tested locally and where to look in the Azure blob storage.

@rcmsoftwaredevelopment Yes sure will add some docs

2021-09-03 08:15 UTC, shepda commented
>     2. Can the docker file under the root directory be amended so for the document storage api removes all dependancies to mongodb.

@rcmsoftwaredevelopment We'll need to leave the mongo connectivity in for now as we'll need it for the migration tool and we can remove it with the migration tool once the migration has been done in prod.

2021-09-03 10:20 UTC, rcmsoftwaredevelopment approved these changes

2021-09-03 10:23 UTC, merged