feat(as-3238): integration of pipeline and structural refactor of azure functions
Planning-Inspectorate/appeal-planning-decision pull request #1671
Opened 2021-09-02 14:54 UTC by demzzydev

integration of pipeline and structural refactor of azure functions

## Ticket Number
AS-3238
https://pins-ds.atlassian.net/browse/AS-

## Description of change

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [ ] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2021-09-02 15:29 UTC, swdpcomputing approved these changes
LGTM

2021-09-02 15:29 UTC, swdpcomputing commented on packages/horizon-functions/azure-functions-pipeline.yml
> +  #    - master
Describe comment-outs please

2021-09-02 22:27 UTC, rcmsoftwaredevelopment requested changes

2021-09-02 22:27 UTC, rcmsoftwaredevelopment commented on packages/horizon-functions/azure-functions-pipeline.yml
> +      - feature/3074b-appeal-service-api-pipeline-tests
Is this branch still valid?

2021-09-03 14:38 UTC, demzzydev commented
Closing PR due to git issues

2021-09-03 14:38 UTC, closed without merging