test: added tests for enforcement notice
Planning-Inspectorate/appeal-planning-decision pull request #1898
Opened 2021-12-03 09:20 UTC by shilpabasu22

## Ticket Number

https://pins-ds.atlassian.net/browse/AS-4017

## Description of change

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [ ] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2021-12-04 23:45 UTC, nssdesikan approved these changes

2021-12-05 00:49 UTC, nssdesikan requested changes

2021-12-05 00:49 UTC, nssdesikan commented on e2e-tests/cypress/integration/before-you-start-enforcement-notice/before-you-start-enforcement-notice-steps.js
> +const pageTitle = 'Have you received an enforcement notice? - Before you start - Appeal a householder planning decision - GOV.UK';
This title is as per the ticket but is this correct? (This is a common page for Householder and other planning decision)

2021-12-08 09:52 UTC, swdpcomputing approved these changes

2021-12-10 11:26 UTC, nssdesikan requested changes

2021-12-10 11:26 UTC, nssdesikan commented on packages/e2e-tests/cypress/integration/full-planning/before-you-start/enforcement-notice.feature
> +    Then appellant is navigated to the type of planning application page
Change the text to _Any of following_

2021-12-10 11:26 UTC, nssdesikan commented on packages/e2e-tests/cypress/integration/full-planning/before-you-start/enforcement-notice/enforcement-notice-steps.js
> +Then('appellant is navigated to the type of planning application page',()=>{
Change the text to _Any of following

2021-12-10 11:35 UTC, shilpabasu22 commented on packages/e2e-tests/cypress/integration/full-planning/before-you-start/enforcement-notice.feature
> +    Then appellant is navigated to the type of planning application page
updated as per review comments

2021-12-10 11:35 UTC, shilpabasu22 commented on packages/e2e-tests/cypress/integration/full-planning/before-you-start/enforcement-notice/enforcement-notice-steps.js
> +Then('appellant is navigated to the type of planning application page',()=>{
updated as per review comments

2021-12-10 11:39 UTC, nssdesikan approved these changes

2021-12-10 13:10 UTC, merged