feat(as-4819 planning obligation deadline): aS-4819 planning obligati…
Planning-Inspectorate/appeal-planning-decision pull request #2442
Opened 2022-05-26 15:09 UTC by manickprabu

…on deadline

## Ticket Number

https://pins-ds.atlassian.net/browse/AS-

## Description of change

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [ ] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `main` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2022-05-26 16:17 UTC, edpackard-work commented on packages/forms-web-app/src/routes/full-appeal/submit-appeal/planning-obligation-deadline.js
> +const planningObligationStatusController = require('../../../controllers/full-appeal/submit-appeal/planning-obligation-deadline');
minor point, but this might be better named `planningObligationDeadlineController` to avoid confusion with `planning-obligation-status.js`

2022-05-26 16:21 UTC, edpackard-work commented on packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/planning-obligation-deadline.test.js
> +});
where is test for post route?

2022-05-26 16:27 UTC, edpackard-work requested changes
all fine, couple of points to address - missing unit tests, and renaming your controller import

2022-05-29 19:10 UTC, manickprabu commented on packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/planning-obligation-deadline.test.js
> +});
resolved.

2022-05-29 19:11 UTC, manickprabu commented on packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/planning-obligation-deadline.test.js
> +});
resolved.

2022-05-30 14:06 UTC, manickprabu commented
this is already had another PR https://github.com/Planning-Inspectorate/appeal-planning-decision/pull/2450

2022-05-30 14:06 UTC, closed without merging