Bug/aapd 82 unable to see added users
Planning-Inspectorate/appeal-planning-decision pull request #2973
Opened 2023-07-27 14:06 UTC by suityou01

## Ticket Number

https://pins-ds.atlassian.net/browse/AAPD-82

## Description of change

Added id param to routes on manage-appeals/your-email-address route

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [x] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `main` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2023-07-28 05:22 UTC, suityou01 commented
> I don't understand this I'm afraid Why would we need to find out the user's email via this login page if we already have the user's id in the url?
> 
> Surely the your email page should not use an id in the url and then on post it should look the user up by email and redirect them onto the enter code with their id in that url?

You and me both. If you look at the controller it expects an id from the url path.

2023-07-28 10:40 UTC, bryn-pins requested changes

2023-07-28 10:40 UTC, bryn-pins commented on packages/forms-web-app/src/controllers/common/your-email-address.js
> +		const id = await getUserByEmail(email);
Believe this returns the actual user so will need to use the _id prop from this method call

Realise there's no jsdocs on the api wrapper and no openapi specs
Was looking into adding some automated openapi specs and will try and find time to achieve that soon

2023-07-31 15:25 UTC, bryn-pins approved these changes

2023-08-01 08:35 UTC, bryn-pins submitted a review, later dismissed

2023-08-01 08:39 UTC, chrishawldev commented
We don't actually need the id in the url, I think this is just from the Heroku template so feel free to just remove the id from the controller action if we don't need it. I'd rather we did that anyway so Google analytics isn't scraping all of our user id's

2023-08-01 08:57 UTC, bryn-pins approved these changes

2023-08-01 09:08 UTC, chrishawldev commented on packages/forms-web-app/src/controllers/common/your-email-address.js
> +		const id = user._id;
Nice one

2023-08-01 16:18 UTC, bryn-pins commented
Closing as fixed in https://github.com/Planning-Inspectorate/appeal-planning-decision/pull/2980

2023-08-01 16:18 UTC, closed without merging