fix(AAPD-347): eslint plugin  to warn about using custom types in cat…
Planning-Inspectorate/appeal-planning-decision pull request #3098
Opened 2023-09-25 13:31 UTC by suityou01

…ch blocks without type guards

## Ticket Number

AAPD-347

https://pins-ds.atlassian.net/browse/AAPD-347

## Description of change

ESLint plugin to detect use of custom types in catch blocks without type guards

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [x] My commit history in this PR is linear
- [x] New features have tests
- [x] Breaking change (team conversation required)

## Important

Please do not merge from `main` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2023-09-28 08:19 UTC, beejjacobs requested changes
Code looks good to me. There are a few bugs though:

If I run this in the root of the repo, I get an error:

```
>npx eslint .

Oops! Something went wrong! :(

ESLint: 8.50.0

TypeError: Cannot read properties of undefined (reading 'name')
Occurred while linting appeal-planning-decision/packages/horizon-functions/horizon-add-document/index.js:124    
Rule: "enforce-catch-block-error-type-guards/enforce-catch-block-error-type-guards"
    at ExpressionStatement (appeal-planning-decision/custom-eslint-rules/catch-blocks/enforce-catch-block-error-type-guards.js:46:36)
    ...
```

A temporary fix of that issue to make it work, and it does pick up the issue in the repo, for example at `src/controllers/appeals-case-data.js:15`

2023-09-28 08:19 UTC, beejjacobs commented on custom-eslint-rules/catch-blocks/enforce-catch-block-error-type-guards.js
> +								if (!ifStatement.test.left.name === param.name) isProblem = true;
This appears to be where the error is, also it'd be clearer as `ifStatement.test.left.name !== param.name` if that is what is intended.

2023-09-28 08:21 UTC, beejjacobs commented on custom-eslint-rules/catch-blocks/enforce-catch-block-error-type-guards.test.js
This errors for me when I run it:

```
appeal-planning-decision\node_modules\eslint\lib\rule-tester\rule-tester.js:458
        throw err;
        ^

Error: Use node.range[1] instead of node.end
Occurred while linting <input>:1
Rule: "enforce-catch-block-error-type-guards"
```

2023-10-25 17:01 UTC, bryn-pins requested changes
There's an issue I've left a comment on that needs fixing.

Played around with this by taking the if check in/out from the listed building route and have 2 more general thoughts

- The fix was applied automatically when using npm run commit which to me feels a bit off due to extremity of the change, would prefer for it to be a suggestion that could be applied after checking it over
- the fix happened after formatting, leaving the indentation wrong

So if we keep to autofix then would prefer an auto formatter to apply as well

2023-10-27 12:11 UTC, bryn-pins approved these changes
I think this is ok now

2023-10-30 16:19 UTC, bryn-pins approved these changes

2023-10-31 10:48 UTC, bryn-pins approved these changes

2023-10-31 13:02 UTC, beejjacobs approved these changes

2023-10-31 14:24 UTC, merged