Feature/aapd 618 implement sql repo
Planning-Inspectorate/appeal-planning-decision pull request #3289
Opened 2023-11-21 10:49 UTC by ms-ek

## Ticket Number

https://pins-ds.atlassian.net/browse/AAPD-618

## Description of change

SQL repository added to query from the database

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [x] My commit history in this PR is linear
- [x] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `main` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2023-11-22 08:33 UTC, beejjacobs requested changes
Looks good. Hopefully a good learning exercise using Prisma.

A few small points to address.

2023-11-22 08:33 UTC, beejjacobs commented on packages/appeals-service-api/src/repositories/sql/appeal-user-repository.js
> +	 * @returns {import('@prisma/client').AppealUser}
This is a promise, so should return `Promise<...type...>`.

Also, won't this return null or something if no user is found?

2023-11-22 08:33 UTC, beejjacobs commented on packages/appeals-service-api/src/services/appeal-user.service.js
> +		throw ApiError.appealsCaseDataNotFound();
I think at this point this would be an unknown error of some kind - assuming `getByEmail` returns null or similar if not found.

2023-11-22 08:33 UTC, beejjacobs commented on packages/appeals-service-api/src/services/appeal-user.service.js
> +const getUserByEmail = async (email) => {
Can we get some jsdoc on here too please?

2023-11-22 08:33 UTC, beejjacobs commented on packages/appeals-service-api/src/controllers/appeals-case-data.js
> +		body = await getUserByEmail('admin1@planninginspectorate.gov.uk');
Let's remove this from the PR, appreciate this was probably a local test :)

2023-11-23 14:52 UTC, beejjacobs reviewed
Looks great! Got a few comments to chat through, nothing major except how we work the testing!

2023-11-23 14:52 UTC, beejjacobs commented on packages/appeals-service-api/src/repositories/sql/appeal-user-repository.js
> +	 * @returns {AppealUser}
Should be `Promise<AppealUser>`?

2023-11-23 14:52 UTC, beejjacobs commented on packages/appeals-service-api/src/repositories/sql/appeal-user-repository.js
> +	 * @returns {AppealUser}
Should be `Promise<AppealUser|null>`?

2023-11-23 14:52 UTC, beejjacobs commented on packages/appeals-service-api/src/routes/index.js
> +router.use('/api/v2/users', appealUsersRouter);
I hadn't thought about this - using the version number is probably a good idea!

2023-11-23 14:52 UTC, beejjacobs commented on packages/appeals-service-api/src/controllers/appeal-user.js
> +async function userGet(req, res) {
For these controllers you can use:

```
/**
 * @type {import('express').Handler}
 */
 ```

2023-11-23 14:52 UTC, beejjacobs commented on packages/appeals-service-api/src/services/appeal-user.service.js
> +const createUser = async (user) => {
Personally I prefer `async function createUser(user)...` format - and that'd be consistent with your controllers, but not a big deal.

2023-11-23 14:52 UTC, beejjacobs commented on packages/appeals-service-api/src/services/appeal-user.service.js
> +	const user = await appealUserRepository.getByEmail(email);
We could check email is defined/a string, and return 400 if not?

2023-11-23 14:52 UTC, beejjacobs commented on packages/appeals-service-api/__tests__/developer/repositories/appeal-user-repository.test.js
I think the other dev/integration tests rely on an instance of mongo. To follow that pattern we'd need an instance of SQL running for this to work. 

We might need to come up with a strategy for this!

2023-11-23 15:04 UTC, bryn-pins commented on packages/appeals-service-api/__tests__/developer/repositories/appeal-user-repository.test.js
looks like the integration tests are failing so need to figure out in this PR

globalSetup.js
const { create } = require('./external-dependencies/database/test-database');
...
test-database.js
const { GenericContainer, Wait } = require('testcontainers/');
new GenericContainer('mongo')

2023-11-23 15:08 UTC, beejjacobs commented on packages/appeals-service-api/__tests__/developer/repositories/appeal-user-repository.test.js
We could just mock Prisma - but then it's less of an integration test and more a unit test. 

https://www.prisma.io/docs/guides/testing/unit-testing#singleton

2023-11-23 15:26 UTC, bryn-pins commented on packages/appeals-service-api/__tests__/developer/repositories/appeal-user-repository.test.js
Have tried this but currently sql container is crashing:

	startedContainer = await new GenericContainer('mcr.microsoft.com/azure-sql-edge:latest')
		.withName('appeals-mssql-integration-tests')
		.withExposedPorts(1433)
		.withWaitStrategy(Wait.forHealthCheck())
		.start();

2023-11-23 15:36 UTC, bryn-pins commented on packages/appeals-service-api/__tests__/developer/repositories/appeal-user-repository.test.js
This seems to work:
	
	let startedContainer2;
	startedContainer2 = await new GenericContainer('mcr.microsoft.com/azure-sql-edge:latest')
		.withName('appeals-mssql-integration-tests')
		.withExposedPorts(1433)
		.withAddedCapabilities('SYS_PTRACE')
		.withUser('root')
		.withEnvironment({ ACCEPT_EULA: '1', MSSQL_SA_PASSWORD: 'DockerDatabaseP@22word!' })
		.withWaitStrategy(Wait.forListeningPorts())
		.start();

2023-11-23 15:56 UTC, ms-ek commented on packages/appeals-service-api/__tests__/developer/repositories/appeal-user-repository.test.js
Would you put this inside the test like in the 'beforeAll' method?

2023-11-23 16:01 UTC, bryn-pins commented on packages/appeals-service-api/__tests__/developer/repositories/appeal-user-repository.test.js
test-database.js

Means we have a sql container running before tests run

However still issue with prisma generate due to the order they run, haven't figured that out yet

2023-11-23 16:35 UTC, ms-ek commented on packages/appeals-service-api/__tests__/developer/repositories/appeal-user-repository.test.js
Does that work for you when you run tests locally?

2023-11-24 11:29 UTC, beejjacobs commented on packages/appeals-service-api/__tests__/developer/repositories/appeal-user-repository.test.js
Good work - testcontainers had a few docs on specific containers, I didn't realise you could just specify any image. 

Maybe we make `startedContainer` an array `startedContainers` ? Then loop through to stop them all.

2023-11-24 14:28 UTC, beejjacobs submitted a review, later dismissed
Review points resolved - thank you, good work.

2023-11-24 16:17 UTC, bryn-pins approved these changes

2023-11-24 16:38 UTC, merged