Feat/aapd 1112/rule 6
Planning-Inspectorate/appeal-planning-decision pull request #3452
Opened 2024-02-22 14:30 UTC by DeanH1990

## Ticket Number

Rule 6 party appeal page sections
https://pins-ds.atlassian.net/browse/AAPD-1112
https://pins-ds.atlassian.net/browse/AAPD-1114
https://pins-ds.atlassian.net/browse/AAPD-1118
https://pins-ds.atlassian.net/browse/AAPD-1120
https://pins-ds.atlassian.net/browse/AAPD-1123

Rule 6 party model
https://pins-ds.atlassian.net/browse/AAPD-1335

## Description of change

This PR adds the sections to the appeal page for the rule 6 party. 
It differentiates the current rule 6 user from other rule 6 parties to show them their documents/ evidence

## Checklist

- [ ] Requires infrastructure changes
- [ ] I have updated the documentation accordingly
- [x] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `main` (please only [rebase](https://github.com/Planning-Inspectorate/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2024-02-22 16:20 UTC, Si3rr4wow approved these changes
Well this turned out to be a lot more work than we made it out to be 😅

2024-02-23 09:05 UTC, beejjacobs requested changes
Apologies, some model change suggestions please.

Rest of the code and implementation looks good. The dynamic part is working well.

2024-02-23 09:05 UTC, beejjacobs commented on packages/forms-web-app/src/controllers/selected-appeal/rule-6-sections.js
> +				}
This worked out quite nicely :)

2024-02-23 11:13 UTC, beejjacobs approved these changes
Good work!

2024-02-23 11:29 UTC, merged