feat(aapd-1502): add api routes for appellant submissions
Planning-Inspectorate/appeal-planning-decision pull request #3508
Opened 2024-03-26 14:17 UTC by Si3rr4wow

## Ticket Number

https://pins-ds.atlassian.net/browse/AAPD-

## Description of change

## Checklist

- [ ] Requires infrastructure changes
- [ ] I have updated the documentation accordingly
- [ ] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `main` (please only [rebase](https://github.com/Planning-Inspectorate/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2024-03-26 16:49 UTC, bryn-pins requested changes
looks good, can we get some tests in though please

2024-03-27 10:00 UTC, Si3rr4wow commented
@bryn-pins ah yep sorry, I forget about them when they're sequestered away in their own dir

2024-04-02 14:44 UTC, DeanH1990 commented on packages/appeals-service-api/src/routes/v2/appellant-submissions/appeallant-submissions.spec.js
small typo in the file name

2024-04-02 14:44 UTC, DeanH1990 submitted a review, later dismissed
Looks good to me!

2024-04-02 14:54 UTC, DeanH1990 approved these changes

2024-04-02 15:11 UTC, merged