feat(lpa-questionnaire-web-app): initial commit new view not yet buil…
Planning-Inspectorate/appeal-planning-decision pull request #556
Opened 2021-02-22 15:24 UTC by marcfielding1

…ding correctly

feat(lpa-questionnaire-web-app): fixed page display problems, ticket draft complete

## Ticket Number
AS-84

## Description of change
Completed view of AS-3

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [X] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2021-02-23 11:54 UTC, davehlewis requested changes
Appears to be missing attributes for testing. Check the test step files to know what is required.

Further to this the tests fail, need to update unit tests for Views file.

2021-02-24 10:15 UTC, davehlewis requested changes

2021-02-24 10:15 UTC, davehlewis commented on packages/lpa-questionnaire-web-app/tests/unit/controllers/extra-conditions.test.js
> +  describe('getOtherAppeals', () => {
name here needs to be updated, left over from copy/paste

2021-02-24 10:25 UTC, davehlewis approved these changes

2021-02-24 15:23 UTC, swdpcomputing approved these changes

2021-02-24 15:23 UTC, merged