Subtask/as 86 connect question to form data
Planning-Inspectorate/appeal-planning-decision pull request #599
Opened 2021-02-26 12:29 UTC by swdpcomputing

## Ticket Number

AS-86

## Description of change

created post, added question to form data

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [x] My commit history in this PR is linear
- [x] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2021-02-26 15:01 UTC, davehlewis requested changes

2021-02-26 15:19 UTC, swdpcomputing commented on packages/lpa-questionnaire-web-app/src/controllers/extra-conditions.js
> +    logger.error(e);
Done

2021-02-26 15:21 UTC, swdpcomputing commented on packages/lpa-questionnaire-web-app/src/controllers/extra-conditions.js
> +const taskName = 'extraConditions';
This is the same as other-appeals so not sure what this refers to.

2021-02-26 15:22 UTC, swdpcomputing commented on packages/lpa-questionnaire-web-app/tests/unit/controllers/extra-conditions.test.js
> +  describe('postOtherAppeals', () => {
Done

2021-02-26 15:22 UTC, swdpcomputing commented on packages/lpa-questionnaire-web-app/tests/unit/controllers/extra-conditions.test.js
> +      // mockAppealReply.sectionStates.extraConditions.extraConditions = mockTaskStatus;
Not needed - deleted.

2021-02-26 15:22 UTC, swdpcomputing commented on packages/lpa-questionnaire-web-app/tests/unit/controllers/extra-conditions.test.js
> +      // mockAppealReply.sectionStates.aboutAppealSection.otherAppeals = mockTaskStatus;
Not needed - deleted.

2021-03-01 15:26 UTC, davehlewis requested changes

2021-03-01 15:26 UTC, davehlewis commented on packages/lpa-questionnaire-web-app/src/controllers/extra-conditions.js
> +    logger.error(e);
Not sure if this was missed but still needs updating

2021-03-01 15:26 UTC, davehlewis commented on packages/lpa-questionnaire-web-app/tests/unit/controllers/extra-conditions.test.js
> +  describe('postOtherAppeals', () => {
Naming is still incorrect here

2021-03-01 16:21 UTC, davehlewis approved these changes

2021-03-01 16:22 UTC, merged