Subtask/as 1192 appeal pdf publish
Planning-Inspectorate/appeal-planning-decision pull request #716
Opened 2021-03-11 19:29 UTC by Fenisay

## Ticket Number

AS-1192
AS-1450
AS-1451
AS-1453
AS-1454
AS-1456
AS-1457

## Description of change

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [ ] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2021-03-11 19:56 UTC, rcmsoftwaredevelopment approved these changes

2021-03-11 20:23 UTC, rcmsoftwaredevelopment approved these changes

2021-03-11 22:26 UTC, Fenisay commented
@MrSimonEmms  Does it still make sense to let the process attempt in the document now that we are not in a cron job ?

2021-03-11 22:44 UTC, rcmsoftwaredevelopment approved these changes

2021-03-12 09:05 UTC, MrSimonEmms requested changes
Can you add the `DOCUMENT_SERVICE_URL` to the `horizon-householder-appeal-publish` in:
 - `/functions.yml`
 - `/charts/functions/values.yaml`
 - `/releases/dev/functions.yml`
 - `/releases/preprod/functions.yml`

I'm happy to do this as part of this PR if you would prefer

2021-03-12 09:07 UTC, MrSimonEmms commented
> @MrSimonEmms Does it still make sense to let the process attempt in the document now that we are not in a cron job ?

I'm happy keeping it in there. I can envisage world where we try to upload immediately and then retry if a problem in future. One would hope that blob storage is reliable enough to never need to do that, but it doesn't affect functionality by being in there and never used

2021-03-12 09:17 UTC, Fenisay commented on packages/forms-web-app/src/services/pdf.service.js
> +    throw new Error(msg);
Probably was your initial idea then someone pinged you on Slack

2021-03-12 09:42 UTC, MrSimonEmms approved these changes

2021-03-12 09:55 UTC, merged