feat(lpa-questionnaire-e2e-tests): added Feature files and step defin…
Planning-Inspectorate/appeal-planning-decision pull request #772
Opened 2021-03-18 09:40 UTC by shilpabasu22

…itions for file upload AS-9

## Ticket Number

AS-9

## Description of change
Adding Feature files and step definitions for AS-9

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [x ] My commit history in this PR is linear
- [x ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2021-03-18 11:06 UTC, swdpcomputing requested changes
Statement: 'Given the Upload the plans used to reach the decision question is requested' needs changing multiple times

2021-03-18 11:20 UTC, shilpabasu22 commented on lpa-submissions-e2e-tests/cypress/integration/uploadThePlansToReachDecision.feature
> +Given the Upload the plans used to reach the decision question is requested
@pippalou I have picked this statement from AS-9. Could you please suggest what needs to be done?

2021-03-19 07:32 UTC, swdpcomputing commented
The feature files still have the line that was going to be edited.

2021-03-19 10:11 UTC, swdpcomputing approved these changes

2021-03-19 10:13 UTC, merged